# Generated by Django 4.2.7 on 2025-07-30 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('workflow_type', models.CharField(choices=[('MESSAGE_APPROVAL', 'موافقة رسالة'), ('DOCUMENT_APPROVAL', 'موافقة وثيقة'), ('TRANSACTION_APPROVAL', 'موافقة معاملة'), ('ACCESS_REQUEST', 'طلب صلاحية'), ('BUDGET_APPROVAL', 'موافقة ميزانية'), ('POLICY_CHANGE', 'تغيير سياسة')], max_length=30)),
                ('template_steps', models.JSONField(default=dict)),
                ('conditions', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'قالب سير العمل',
                'verbose_name_plural': 'قوالب سير العمل',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('workflow_type', models.CharField(choices=[('MESSAGE_APPROVAL', 'موافقة رسالة'), ('DOCUMENT_APPROVAL', 'موافقة وثيقة'), ('TRANSACTION_APPROVAL', 'موافقة معاملة'), ('ACCESS_REQUEST', 'طلب صلاحية'), ('BUDGET_APPROVAL', 'موافقة ميزانية'), ('POLICY_CHANGE', 'تغيير سياسة')], max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('requires_sequential_approval', models.BooleanField(default=True, verbose_name='يتطلب موافقة متسلسلة')),
                ('minimum_approvers', models.IntegerField(default=1, verbose_name='الحد الأدنى للموافقين')),
                ('auto_approve_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('applicable_departments', models.ManyToManyField(blank=True, to='accounts.department')),
            ],
            options={
                'verbose_name': 'سير عمل الموافقة',
                'verbose_name_plural': 'سير عمل الموافقات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('content_type', models.CharField(max_length=50)),
                ('object_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('justification', models.TextField(blank=True, verbose_name='المبرر')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(blank=True, default='SAR', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'في الانتظار'), ('IN_PROGRESS', 'قيد المراجعة'), ('APPROVED', 'موافق عليه'), ('REJECTED', 'مرفوض'), ('CANCELLED', 'ملغى'), ('EXPIRED', 'منتهي الصلاحية')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('priority_level', models.IntegerField(default=3)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflows.approvalworkflow')),
            ],
            options={
                'verbose_name': 'طلب موافقة',
                'verbose_name_plural': 'طلبات الموافقة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.IntegerField()),
                ('action', models.CharField(blank=True, choices=[('APPROVE', 'موافقة'), ('REJECT', 'رفض'), ('REQUEST_INFO', 'طلب معلومات'), ('DELEGATE', 'تفويض'), ('SKIP', 'تخطي')], max_length=20, null=True)),
                ('comments', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_current_step', models.BooleanField(default=False)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_steps', to=settings.AUTH_USER_MODEL)),
                ('delegated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_approvals', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='workflows.approvalrequest')),
            ],
            options={
                'ordering': ['step_order'],
                'unique_together': {('request', 'step_order')},
            },
        ),
    ]
