# Generated by Django 5.0.2 on 2025-07-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['name'], name='accounts_de_name_4ee611_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['code'], name='accounts_de_code_b809b1_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['employee_id'], name='accounts_us_employe_0cbd94_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['department', 'position'], name='accounts_us_departm_0ab2e4_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'is_staff'], name='accounts_us_is_acti_4cba6b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_activity'], name='accounts_us_last_ac_d21a25_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username', 'is_active'], name='accounts_us_usernam_94d178_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['delegation_start_date', 'delegation_end_date'], name='accounts_us_delegat_c2ffea_idx'),
        ),
    ]
