# Generated by Django 5.0.2 on 2025-07-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_department_is_active_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['is_active'], name='accounts_de_is_acti_0ea50a_idx'),
        ),
    ]
