# Generated by Django 5.0.2 on 2025-07-31 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_update_phone_to_3_digits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='max_approval_amount',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{3}$', 'رقم الهاتف يجب أن يتألف من 3 أرقام فقط')], verbose_name='رقم الهاتف'),
        ),
    ]
