# Generated by Django 5.0.2 on 2025-07-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_max_approval_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='max_approval_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='أقصى مبلغ للموافقة'),
        ),
    ]
