# Generated by Django 4.2.7 on 2025-07-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('LOGIN', 'تسجيل دخول'), ('LOGOUT', 'تسجيل خروج'), ('MESSAGE_SEND', 'إرسال رسالة'), ('MESSAGE_READ', 'قراءة رسالة'), ('MESSAGE_DELETE', 'حذف رسالة'), ('FILE_UPLOAD', 'رفع ملف'), ('FILE_DOWNLOAD', 'تحميل ملف'), ('ADMIN_ACTION', 'إجراء إداري'), ('SECURITY_VIOLATION', 'مخالفة أمنية'), ('FAILED_LOGIN', 'فشل تسجيل دخول')], max_length=30),
        ),
    ]
