# Generated by Django 5.0.2 on 2025-07-31 14:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_alter_auditlog_action_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('LOGIN', 'تسجيل دخول'), ('LOGOUT', 'تسجيل خروج'), ('ADMIN_LOGIN', 'تسجيل دخول المدير'), ('ADMIN_LOGOUT', 'تسجيل خروج المدير'), ('UNAUTHORIZED_ACCESS', 'محاولة وصول غير مصرح'), ('MESSAGE_SEND', 'إرسال رسالة'), ('MESSAGE_READ', 'قراءة رسالة'), ('MESSAGE_DELETE', 'حذف رسالة'), ('FILE_UPLOAD', 'رفع ملف'), ('FILE_DOWNLOAD', 'تحميل ملف'), ('ADMIN_ACTION', 'إجراء إداري'), ('SECURITY_VIOLATION', 'مخالفة أمنية'), ('FAILED_LOGIN', 'فشل تسجيل دخول')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-timestamp'], name='security_au_user_id_6d8368_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_type', '-timestamp'], name='security_au_action__33a154_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user_ip', '-timestamp'], name='security_au_user_ip_7ab551_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['is_successful', '-timestamp'], name='security_au_is_succ_ef89ad_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-timestamp'], name='security_au_timesta_cbae00_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['username', '-timestamp'], name='security_lo_usernam_6d99d9_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['ip_address', '-timestamp'], name='security_lo_ip_addr_622cb0_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['is_successful', '-timestamp'], name='security_lo_is_succ_1f96d1_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['-timestamp'], name='security_lo_timesta_98b512_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', '-login_time'], name='security_us_user_id_92356f_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_key'], name='security_us_session_cd98d8_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['is_active', '-last_activity'], name='security_us_is_acti_e219c9_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['ip_address', '-login_time'], name='security_us_ip_addr_206167_idx'),
        ),
    ]
