# Generated by Django 5.0.2 on 2025-08-02 14:14

import django.core.validators
import django.db.models.deletion
import messaging.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CREDIT', 'ائتمان'), ('TREASURY', 'خزينة'), ('OPERATIONS', 'عمليات'), ('ADMIN', 'إدارية'), ('HR', 'موارد بشرية'), ('IT', 'تقنية المعلومات'), ('COMPLIANCE', 'امتثال'), ('AUDIT', 'مراجعة'), ('CUSTOMER', 'خدمة العملاء'), ('OTHER', 'أخرى')], max_length=50, unique=True, verbose_name='اسم التصنيف')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='يتطلب موافقة')),
                ('default_priority', models.CharField(default='NORMAL', max_length=20, verbose_name='الأولوية الافتراضية')),
            ],
            options={
                'verbose_name': 'تصنيف الرسالة',
                'verbose_name_plural': 'تصنيفات الرسائل',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='معرف الرسالة')),
                ('sequence_number', models.CharField(max_length=20, unique=True, verbose_name='الرقم التسلسلي')),
                ('subject', models.CharField(max_length=200, verbose_name='الموضوع')),
                ('body', models.TextField(verbose_name='نص الرسالة')),
                ('priority', models.CharField(choices=[('LOW', 'عادية'), ('NORMAL', 'متوسطة'), ('HIGH', 'مهمة'), ('URGENT', 'عاجلة'), ('CRITICAL', 'حرجة')], default='NORMAL', max_length=20, verbose_name='الأولوية')),
                ('confidentiality', models.CharField(choices=[('PUBLIC', 'عامة'), ('INTERNAL', 'داخلية'), ('CONFIDENTIAL', 'سرية'), ('TOP_SECRET', 'سرية للغاية')], default='INTERNAL', max_length=20, verbose_name='مستوى السرية')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('SENT', 'مرسلة'), ('RECEIVED', 'مستلمة'), ('READ', 'مقروءة'), ('REPLIED', 'مجاب عليها'), ('FORWARDED', 'محولة'), ('ARCHIVED', 'مؤرشفة'), ('DELETED', 'محذوفة')], default='DRAFT', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('reference_number', models.CharField(blank=True, max_length=50, verbose_name='رقم المرجع')),
                ('account_number', models.CharField(blank=True, max_length=20, verbose_name='رقم الحساب')),
                ('transaction_reference', models.CharField(blank=True, max_length=50, verbose_name='مرجع المعاملة')),
                ('is_encrypted', models.BooleanField(default=True, verbose_name='مشفرة')),
                ('digital_signature', models.TextField(blank=True, verbose_name='التوقيع الرقمي')),
                ('hash_value', models.CharField(blank=True, max_length=64, verbose_name='قيمة التشفير')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='انتهاء الصلاحية')),
                ('auto_delete_at', models.DateTimeField(blank=True, null=True, verbose_name='الحذف التلقائي')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الأرشفة')),
                ('prevent_forwarding', models.BooleanField(default=False, verbose_name='منع التحويل')),
                ('require_read_receipt', models.BooleanField(default=False, verbose_name='يتطلب إيصال قراءة')),
                ('forwarded_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forwards', to='messaging.message', verbose_name='محول من')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='messaging.message', verbose_name='رد على')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='messaging.messagecategory', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'الرسالة',
                'verbose_name_plural': 'الرسائل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=messaging.models.message_attachment_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'jpg', 'png'])], verbose_name='الملف')),
                ('original_filename', models.CharField(max_length=255, verbose_name='اسم الملف الأصلي')),
                ('file_size', models.BigIntegerField(verbose_name='حجم الملف')),
                ('mime_type', models.CharField(max_length=100, verbose_name='نوع الملف')),
                ('is_encrypted', models.BooleanField(default=True, verbose_name='مشفر')),
                ('checksum', models.CharField(max_length=64, verbose_name='المجموع التحققي')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='messaging.message', verbose_name='الرسالة')),
            ],
            options={
                'verbose_name': 'مرفق الرسالة',
                'verbose_name_plural': 'مرفقات الرسائل',
            },
        ),
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'إنشاء'), ('SENT', 'إرسال'), ('READ', 'قراءة'), ('REPLIED', 'رد'), ('FORWARDED', 'تحويل'), ('ARCHIVED', 'أرشفة'), ('DELETED', 'حذف'), ('MODIFIED', 'تعديل')], max_length=20, verbose_name='الإجراء')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
                ('details', models.TextField(blank=True, verbose_name='التفاصيل')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='معلومات المتصفح')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='messaging.message', verbose_name='الرسالة')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='نُفذ بواسطة')),
            ],
            options={
                'verbose_name': 'تاريخ الرسالة',
                'verbose_name_plural': 'تاريخ الرسائل',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MessageRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('TO', 'إلى'), ('CC', 'نسخة'), ('BCC', 'نسخة مخفية')], default='TO', max_length=10, verbose_name='نوع المستقبل')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القراءة')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإقرار')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوفة')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.message', verbose_name='الرسالة')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستقبل')),
            ],
            options={
                'verbose_name': 'مستقبل الرسالة',
                'verbose_name_plural': 'مستقبلو الرسائل',
                'unique_together': {('message', 'recipient')},
            },
        ),
        migrations.AddField(
            model_name='message',
            name='recipients',
            field=models.ManyToManyField(related_name='received_messages', through='messaging.MessageRecipient', to=settings.AUTH_USER_MODEL, verbose_name='المستقبلون'),
        ),
        migrations.CreateModel(
            name='DigitalSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='معرف التوقيع')),
                ('signature_type', models.CharField(choices=[('APPROVAL', 'موافقة'), ('REPLY', 'رد'), ('FORWARD', 'تحويل'), ('ACKNOWLEDGEMENT', 'إقرار'), ('REJECTION', 'رفض')], max_length=20, verbose_name='نوع التوقيع')),
                ('reason', models.TextField(blank=True, verbose_name='سبب التوقيع')),
                ('signature_data', models.JSONField(verbose_name='بيانات التوقيع')),
                ('hash_value', models.CharField(max_length=64, verbose_name='قيمة التشفير')),
                ('qr_code', models.ImageField(upload_to=messaging.models.signature_qr_path, verbose_name='رمز QR')),
                ('qr_data', models.TextField(verbose_name='بيانات QR')),
                ('ip_address', models.GenericIPAddressField(verbose_name='عنوان IP')),
                ('user_agent', models.TextField(verbose_name='معلومات المتصفح')),
                ('location_info', models.JSONField(blank=True, null=True, verbose_name='معلومات الموقع')),
                ('signed_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت التوقيع')),
                ('expires_at', models.DateTimeField(verbose_name='انتهاء الصلاحية')),
                ('verification_status', models.CharField(choices=[('VALID', 'صالح'), ('EXPIRED', 'منتهي الصلاحية'), ('REVOKED', 'ملغي'), ('INVALID', 'غير صالح')], default='VALID', max_length=20, verbose_name='حالة التحقق')),
                ('certificate_serial', models.CharField(blank=True, max_length=50, verbose_name='رقم الشهادة')),
                ('verification_url', models.URLField(blank=True, verbose_name='رابط التحقق')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='الموقع')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_signatures', to='messaging.message', verbose_name='الرسالة')),
            ],
            options={
                'verbose_name': 'التوقيع الرقمي',
                'verbose_name_plural': 'التوقيعات الرقمية',
                'ordering': ['-signed_at'],
                'indexes': [models.Index(fields=['signature_id'], name='messaging_d_signatu_fcf8fc_idx'), models.Index(fields=['message', 'signer'], name='messaging_d_message_e17d55_idx'), models.Index(fields=['verification_status', 'expires_at'], name='messaging_d_verific_c8483a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', '-created_at'], name='messaging_m_sender__9b0bb2_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['category', '-created_at'], name='messaging_m_categor_83bc24_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['priority', '-created_at'], name='messaging_m_priorit_1aaeff_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['reference_number'], name='messaging_m_referen_be0d85_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['account_number'], name='messaging_m_account_40bbfd_idx'),
        ),
    ]
